---
watch: true
import: true
sources:
  - test.pdf
  - ~/Documents/Scanner/
rules:
  - match: ".*arbeiterempfehlung.*"
    extract:
      - key: personalnummer
        match: ".*Personalnummer: ([0-9]*).*"
    target: "./processed/{extract[personalnummer]}.pdf"
  - match: "Bewerbung"
    target: "boo"
  - match: "Internet"
    target: "boo"
  - match: "Foo"
    target: "\\1"
