---
watch: true
import: true
sources:
  - ~/Documents/Scanner/
rules:
  - search: ".*arbeiterempfehlung.*"
    extract:
      - key: personalnummer
        search: ".*Personalnummer: ([0-9]*).*"
    target: "./processed/{extract[personalnummer]}.pdf"
  - search: "Bewerbung"
    target: "./processed/boo.pdf"
  - search: "Internet"
    target: "boo"
  - search: "Foo"
    target: "./processed/Foo.pdf"
